"""NASA Exoplanet Watch submission formatter.

Exoplanet Watch (https://exoplanets.nasa.gov/exoplanet-watch/) accepts
AAVSO Exoplanet Section format light curves. The Exoplanet Section
format is a CSV with a metadata header block.

Header block (lines beginning with #):
  #TYPE=EXOPLANET
  #OBSCODE=ATLAS01
  #SOFTWARE=ATLAS
  #DELIM=,
  #DATE_TYPE=BJD_TDB
  #OBSTYPE=CCD
  #STAR_NAME=TOI-1234.01
  #EXOPLANET_NAME=TOI-1234 b
  #BINNING=1x1
  #EXPOSURE_TIME=60
  #FILTER=Rc
  #DETECTOR=ASI2600MM
  #PIXEL_SCALE=0.5
  #FIELD_ROTATION=No
  #PRIORS_USED= (planet ephemeris source)
  #COMMENT=Comp star 1: TIC123 mag 12.5
  #COMMENT=Comp star 2: TIC456 mag 12.8

Then CSV rows:
  BJD_TDB,REL_FLUX,REL_FLUX_ERR,AIRMASS,EXPOSURE,COMP_FLUX_1,COMP_FLUX_2

Each row is one frame's differential photometry result.

This module formats from a single Measurement of kind=photometry
where the value dict carries the full time series (one row per
captured frame in the transit window).
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from atlas.science.submissions.base import SubmissionPayload, Submitter


class NasaEoSubmitter(Submitter):
    destination = "nasa_exoplanet_watch"

    def __init__(self, *, obscode: str = "ATLAS01",
                   software: str = "ATLAS",
                   detector: str = "ASI2600MM",
                   pixel_scale_arcsec: float = 0.5):
        self._obscode = obscode
        self._software = software
        self._detector = detector
        self._pixel_scale = float(pixel_scale_arcsec)

    def format(self, measurement_row: dict) -> SubmissionPayload:
        """Build an AAVSO Exoplanet Section-compatible CSV.

        Expected measurement_row.value shape (from ExoplanetWorkflow
        process() output):
            {
              "star_name": "TOI-1234.01",
              "exoplanet_name": "TOI-1234 b",
              "filter": "Rc",
              "binning": "1x1",
              "comp_stars": [
                  {"id": "TIC123", "mag": 12.5},
                  {"id": "TIC456", "mag": 12.8},
              ],
              "priors_source": "ExoFOP-TESS",
              "remarks": "ingress + transit + egress; good seeing",
              "rows": [
                  {"bjd_tdb": 2461125.23456,
                   "rel_flux": 1.0001,
                   "rel_flux_err": 0.0009,
                   "airmass": 1.21,
                   "exposure_s": 60.0,
                   "comp_fluxes": [1.0023, 1.0019]},
                   ...
              ],
            }
        """
        v = measurement_row.get("value") or {}
        rows = v.get("rows") or []

        # ---- header block ----
        header_lines: list[str] = [
            "#TYPE=EXOPLANET",
            f"#OBSCODE={self._obscode}",
            f"#SOFTWARE={self._software}",
            "#DELIM=,",
            "#DATE_TYPE=BJD_TDB",
            "#OBSTYPE=CCD",
            f"#STAR_NAME={v.get('star_name','')}",
            f"#EXOPLANET_NAME={v.get('exoplanet_name','')}",
            f"#BINNING={v.get('binning','1x1')}",
        ]
        # Exposure: pull from first row if present, fall back to scalar field
        first_exp = None
        if rows:
            first_exp = rows[0].get("exposure_s")
        if first_exp is None:
            first_exp = v.get("exposure_s", 60.0)
        header_lines.append(f"#EXPOSURE_TIME={float(first_exp):.0f}")
        header_lines.append(f"#FILTER={v.get('filter','Rc')}")
        header_lines.append(f"#DETECTOR={self._detector}")
        header_lines.append(f"#PIXEL_SCALE={self._pixel_scale:.2f}")
        header_lines.append("#FIELD_ROTATION=No")
        if v.get("priors_source"):
            header_lines.append(f"#PRIORS_USED={v['priors_source']}")
        for cs in (v.get("comp_stars") or []):
            cs_id = cs.get("id", "?")
            cs_mag = cs.get("mag", "?")
            header_lines.append(f"#COMMENT=Comp star: {cs_id} mag {cs_mag}")
        if v.get("remarks"):
            header_lines.append(f"#COMMENT={v['remarks']}")
        header_lines.append(f"#COMMENT=Generated by {self._software} "
                              f"{datetime.utcnow().isoformat(timespec='seconds')}Z")

        # ---- column header ----
        n_comps = max((len(r.get("comp_fluxes") or []) for r in rows),
                          default=0)
        column_header_parts = [
            "BJD_TDB", "REL_FLUX", "REL_FLUX_ERR",
            "AIRMASS", "EXPOSURE",
        ]
        for i in range(n_comps):
            column_header_parts.append(f"COMP_FLUX_{i+1}")
        column_header = ",".join(column_header_parts)

        # ---- data rows ----
        data_lines: list[str] = []
        for r in rows:
            parts = [
                f"{r.get('bjd_tdb', 0):.6f}",
                f"{r.get('rel_flux', 0):.6f}",
                f"{r.get('rel_flux_err', 0):.6f}",
                f"{r.get('airmass', 0):.3f}",
                f"{r.get('exposure_s', 0):.1f}",
            ]
            comps = r.get("comp_fluxes") or []
            for i in range(n_comps):
                if i < len(comps):
                    parts.append(f"{comps[i]:.6f}")
                else:
                    parts.append("")
            data_lines.append(",".join(parts))

        text = "\n".join(header_lines + [column_header] + data_lines) + "\n"
        return SubmissionPayload(
            text=text, content_type="text/csv",
            metadata={
                "obscode": self._obscode,
                "star_name": v.get("star_name", ""),
                "exoplanet_name": v.get("exoplanet_name", ""),
                "filter": v.get("filter", "Rc"),
                "n_rows": len(rows),
                "n_comp_stars": n_comps,
            },
        )

    async def send(self, payload: SubmissionPayload) -> dict:
        """Upload to NASA Exoplanet Watch. Their accepted ingest path
        currently is email upload to exoplanetwatch@jpl.nasa.gov or the
        AAVSO Exoplanet Section web form. We wire one of those on bench
        day with real credentials; for now we just stage the payload.
        """
        return {"ok": False,
                  "error": ("NASA Exoplanet Watch endpoint not yet wired — "
                              "payload formatted, ready for email/form upload "
                              "on bench day"),
                  "preview_first_200_chars": payload.text[:200]}
